#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0

//Left hand home row modifiers
#define HOME_A LCTL_T(KC_A)
#define HOME_S LSFT_T(KC_S)
#define HOME_D LALT_T(KC_D)

//Right hand home row modifiers
#define HOME_SCLN RCTL_T(KC_SCLN)
#define HOME_L RSFT_T(KC_L)
#define HOME_K LALT_T(KC_K)

// Default keypress section 
enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_GRV, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_TAB, HOME_A, HOME_S, HOME_D, KC_F, KC_G, KC_H, KC_J, HOME_K, HOME_L, HOME_SCLN, KC_QUOT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_ESC, CW_TOGG, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LGUI, KC_LALT, KC_BSPC, MO(3), MO(4), MEH_T(KC_SPC), KC_RSFT, KC_ENT),

[_LAYER1] = LAYOUT(KC_GRV, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC, KC_TAB, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_ENT, KC_LCTL, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_ESC, CW_TOGG, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_SLSH, KC_LGUI, KC_LALT, KC_BSPC, MO(3), MO(4), KC_SPC, KC_RSFT, KC_ENT),

[_LAYER2] = LAYOUT(KC_GRV, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC, KC_TAB, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_ENT, KC_LCTL, KC_Z, KC_TRNS, KC_C, KC_D, KC_V, KC_ESC, CW_TOGG, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_QUOT, KC_LGUI, KC_LALT, KC_BSPC, MO(3), MO(4), KC_SPC, KC_RSFT, KC_ENT),

[_LAYER3] = LAYOUT(LCTL(KC_Z), LCTL(KC_Y), KC_F1, KC_F2, KC_F3, KC_F4, KC_7, KC_8, KC_9, KC_PSCR, KC_SCRL, KC_PAUS, LCTL(KC_X), KC_LGUI, KC_F5, KC_F6, KC_F7, KC_F8, KC_4, KC_5, KC_6, KC_INS, KC_HOME, KC_PGUP, LCTL(KC_C), LCTL(KC_V), KC_F9, KC_F10, KC_F11, KC_F12, LCTL(KC_Z), LCTL(KC_Y), KC_1, KC_2, KC_3, KC_DEL, KC_END, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(5), KC_TRNS, KC_0, KC_PDOT),

[_LAYER4] = LAYOUT(KC_GRV, KC_GRV, KC_UP, KC_MPLY, KC_MRWD, KC_EQL, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_MINS, KC_EQL, KC_TAB, KC_LEFT, KC_DOWN, KC_RGHT, KC_PSLS, KC_PMNS, KC_DLR, KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_PIPE, KC_UNDS, KC_PLUS, KC_PIPE, KC_UNDS, OSM(MOD_RALT), KC_APP, KC_EXLM, KC_AT, KC_HASH, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, MO(5), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER5] = LAYOUT(KC_NO, DF(6), DF(0), DF(2), AG_SWAP, CG_SWAP, KC_NO, KC_F11, KC_F12, KC_PSCR, KC_NO, EE_CLR, KC_NO, KC_NO, KC_BRID, KC_BRIU, AG_NORM, CG_NORM, RGB_MOD, RGB_VAI, RGB_HUI, RGB_SAI, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, RGB_TOG, RGB_RMOD, RGB_VAD, RGB_HUD, RGB_SAD, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),

[_LAYER6] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_RSFT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_ESC, KC_NO, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RCTL, KC_LGUI, KC_LALT, KC_SPC, MO(3), MO(4), KC_SPC, KC_RALT, KC_ENT) 

};

//Combo section
const uint16_t PROGMEM openParenCombo[] = {KC_Y, KC_U, COMBO_END};
const uint16_t PROGMEM closeParenCombo[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM openBraceCombo[] = {KC_H, KC_J, COMBO_END};
const uint16_t PROGMEM closeBraceCombo[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM openBracketCombo[] = {KC_N, KC_M, COMBO_END};
const uint16_t PROGMEM closeBracketCombo[] = {KC_M, KC_COMM, COMBO_END};
const uint16_t PROGMEM dashCombo[] = {KC_R, KC_T, COMBO_END};
const uint16_t PROGMEM underscoreCombo[] = {KC_F, KC_G, COMBO_END};
const uint16_t PROGMEM equalsCombo[] = {KC_V, KC_B, COMBO_END};

combo_t key_combos[] = {
	COMBO(openParenCombo, KC_LPRN),
	COMBO(closeParenCombo, KC_RPRN),
	COMBO(openBraceCombo, KC_LCBR),
	COMBO(closeBraceCombo, KC_RCBR),
	COMBO(openBracketCombo, KC_LBRC),
	COMBO(closeBracketCombo, KC_RBRC),
	COMBO(dashCombo, KC_PMNS),
	COMBO(underscoreCombo, KC_UNDS),
	COMBO(equalsCombo, KC_EQL)
};